version: "3"

services:
  affiliate-forwarder:
    # You can build the image yourself or use the pre-built image from Docker Hub
    # build: .
    image: "laoliu233/affiliate-forwarder:latest"
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - "./config.json:/app/config.json:ro"
    environment:
      - AFF_FWD_CONF_PATH=/app/config.json